# Generated by Django 5.2.14 on 2026-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_requier',
            field=models.BooleanField(default=False),
        ),
    ]
